spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.20:3306/seata_pay?useUnicode=true&rewriteBatchedStatements=true
    username: root
    password: test
logging:
  level:
    com.maoyou.testseata.pay.mapper: debug
seata:
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 192.168.56.20:8091
